/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.smata.clientes.ventanas;

import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maquina 1
 */
public class VentanaMaestra extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMaestra
     */public int  ancho = 1200;
        public int alto = 900;
    public VentanaMaestra() {
        
        initComponents();
        
        this.setSize(ancho,alto);// buscar fomra de maximizar directo, y centrar ventanas que llame
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_datos = new javax.swing.JMenu();
        mnItemDatos = new javax.swing.JMenuItem();
        mnItemBuscar = new javax.swing.JMenuItem();
        mn_calendario = new javax.swing.JMenu();
        mn_VerCal = new javax.swing.JMenuItem();
        mn_cursos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mn_ayuda = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mn_datos.setText("Adultos");
        mn_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datosActionPerformed(evt);
            }
        });

        mnItemDatos.setText("Datos");
        mnItemDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDatosActionPerformed(evt);
            }
        });
        mn_datos.add(mnItemDatos);

        mnItemBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        mnItemBuscar.setText("Buscar");
        mnItemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemBuscarActionPerformed(evt);
            }
        });
        mn_datos.add(mnItemBuscar);

        jMenuBar1.add(mn_datos);

        mn_calendario.setText("Calendario");

        mn_VerCal.setText("Ver Calendario");
        mn_VerCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_VerCalActionPerformed(evt);
            }
        });
        mn_calendario.add(mn_VerCal);

        jMenuBar1.add(mn_calendario);

        mn_cursos.setText("Mis cusos");
        jMenuBar1.add(mn_cursos);

        jMenu2.setText("Ayuda");

        mn_ayuda.setText("Acerca de...");
        mn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ayudaActionPerformed(evt);
            }
        });
        jMenu2.add(mn_ayuda);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnItemDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDatosActionPerformed
       
        VentanaDatos v=null;
         try {
             v = new VentanaDatos();
         } catch (IOException ex) {
             Logger.getLogger(VentanaMaestra.class.getName()).log(Level.SEVERE, null, ex);
         }
        jDesktopPane1.add(v);
         Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = v.getSize();
        v.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        v.show();  
        v.setVisible(true);
    }//GEN-LAST:event_mnItemDatosActionPerformed

    private void mn_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datosActionPerformed
        
    }//GEN-LAST:event_mn_datosActionPerformed

    private void mnItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemBuscarActionPerformed
       
        VentanaBuscar vb = new VentanaBuscar ();
        jDesktopPane1.add(vb);
         Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = vb.getSize();
        vb.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        vb.show();  
        vb.setVisible(true);
        
        
    }//GEN-LAST:event_mnItemBuscarActionPerformed

    private void mn_VerCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_VerCalActionPerformed
        
        VentanaCalendario vCal = new VentanaCalendario();
        jDesktopPane1.add(vCal);
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = vCal.getSize();
        vCal.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        vCal.show();  
        vCal.setVisible(true);
        
    }//GEN-LAST:event_mn_VerCalActionPerformed

    private void mn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ayudaActionPerformed
//       VentanaAcercaDe vAcDe = new VentanaAcercaDe(ancho,alto);
        VentanaAcercaDe vAcDe = new VentanaAcercaDe();
        
        jDesktopPane1.add(vAcDe);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = vAcDe.getSize();
        vAcDe.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        vAcDe.show();  
        vAcDe.setVisible(true);
       
        
        
    }//GEN-LAST:event_mn_ayudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMaestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnItemBuscar;
    private javax.swing.JMenuItem mnItemDatos;
    private javax.swing.JMenuItem mn_VerCal;
    private javax.swing.JMenuItem mn_ayuda;
    private javax.swing.JMenu mn_calendario;
    private javax.swing.JMenu mn_cursos;
    private javax.swing.JMenu mn_datos;
    // End of variables declaration//GEN-END:variables
}
